# Matrix Hacker Theme for Kitty

foreground            #00ff88
background            #1a1b26

selection_foreground  #000000
selection_background  #00ff41

cursor                #00ff41
cursor_text_color     #000000

# Negro
color0  #414868
color8  #414868

# Verde oscuro
color2  #7dcfff
color10 #00ff88

# Verde brillante
color3  #66cc33
color11 #66cc33

# Verde lima
color4  #33ff66
color12 #66ff99

# Verde neón
color5  #00ff88
color13 #00ff88

# Verde cian
color6  #73daca
color14 #73daca

# Blanco verdoso
color7  #c8ffd0
color15 #e8ffe8

# Rojo (errores)
color1  #f7768e
color9  #f7768e

# Amarillo (advertencias)
color3  #e0af68
color11 #e0af68

# URLs
url_color #00ff88

# Bordes
active_border_color   #00ff41
inactive_border_color #0f2f0f

# Tabs
active_tab_background   #00aa00
active_tab_foreground   #000000
inactive_tab_background #0b160b
inactive_tab_foreground #55aa55
